### ISSUE TITLE
NRC semiannual reports aren't in a table anymore

### ISSUE THREAD

**Issue by handlers** [unitedstates/inspectors-general#200]
```
Traceback (most recent call last):

  File "inspectors/utils/utils.py", line 34, in run
    return run_method(cli_options)

  File "inspectors/nrc.py", line 67, in run
    for index, result in enumerate(semiannual_reports_table.select("tr")):

AttributeError: 'NoneType' object has no attribute 'select'
```

Working on a fix.

**Comment by spulec** [comment]
It looks like this was taken care of with #201
